FROM rocker/r-ver:4.3.1

LABEL org.opencontainers.image.licenses="GPL-2.0-or-later" \
      org.opencontainers.image.source="https://github.com/rocker-org/rocker-versioned2" \
      org.opencontainers.image.vendor="Rocker Project" \
      org.opencontainers.image.authors="Carl Boettiger <cboettig@ropensci.org>"

ENV S6_VERSION=v2.1.0.2
ENV RSTUDIO_VERSION=2023.09.1+494
ENV DEFAULT_USER=rstudio
ENV PANDOC_VERSION=default
ENV QUARTO_VERSION=default

RUN /rocker_scripts/install_rstudio.sh
RUN /rocker_scripts/install_pandoc.sh
RUN /rocker_scripts/install_quarto.sh

RUN apt-get update && apt-get install -y optipng \
                                         pandoc \
                                         libpng-dev \
                                         zlib1g-dev \
                                         libssl-dev \
                                         liblzma-dev \
                                         libbz2-dev \
                                         libglpk-dev \
                                         libcurl4-openssl-dev \
                                         python-tk  \
                                         python3-tk \
                                         tk-dev

# Install system library for rgeos
RUN apt-get install -y libgeos-dev #needed for new version of seurat
RUN apt-get install -y libcairo2-dev #needed for ComplexHeatmap and scCustomize
RUN apt-get install -y libxt-dev  #needed for ComplexHeatmap and scCustomize
#C library needed for the R pacakges

# Install basic R packages
RUN R -e 'install.packages( "devtools")'
RUN R -e 'install.packages( "BiocManager")'
RUN R -e 'BiocManager::install(version="3.18")'

RUN R -e 'BiocManager::install("zellkonverter")'

# Install Seurat packages and dependencies
RUN R -e 'install.packages("Matrix")'
RUN R -e 'install.packages("SeuratObject")'
RUN R -e 'BiocManager::install("Seurat")' 

# test AnndataR
RUN apt-get install -y libhdf5-dev
RUN R -e 'install.packages("pak")'
RUN R -e 'install.packages("hdf5r")'
RUN R -e 'pak::pak("scverse/anndataR")'



EXPOSE 8787

CMD ["/init"]