---
title: "RNA_TCGA_BEX"
output: html_document
date: "2024-01-23"
editor_options: 
  chunk_output_type: console
---
########

Code made for RNA431 docker
To build TCGA-TALL obj in an RNA docker and not with Seurat

########


```{r setup, include=FALSE}
library(TCGAbiolinks)
library(DESeq2)
install.packages("tidyverse")
library(tidyverse) #load all tidyverse suite : ggplot2,dplyr...
library(DT)
library(ComplexHeatmap)
install.packages("paletteer")
library(paletteer)
```


Set your working directory to the folder clone from github
```{r}
setwd("/workspace/NASBioinfo/LALT/BIOINFO/BEX/TCGA/")
WORK_DIR <- "../BEX"
```


# FIGURE

### T-ALL
```{r}
#testing
TARGET_DESeqTALL <- DESeqDataSetFromMatrix(countData=RNA_matrix_TARGET_TALL, 
                              colData=clinical_matrix_TARGET_TALL, 
                              design= ~ detailed_class)

TARGET_DESeqTALL <- DESeq(TARGET_DESeqTALL)
```

#### load final matrix
```{r}
clinical_matrix_TARGET_TALL <- readRDS("/workspace/NASBioinfo/LALT/BIOINFO/BEX/TO_UPLOAD_FOR GIT/DATA/BUlkRNA/clinical_matrix_TARGET_TALL.rds")
RNA_matrix_TARGET_TALL <- readRDS("/workspace/NASBioinfo/LALT/BIOINFO/BEX/TO_UPLOAD_FOR GIT/DATA/BUlkRNA/RNA_matrix_TARGET_TALL_convert.rds")

table(clinical_matrix_TARGET_TALL$detailed_class)
```

#### PCA plot
```{r}
# PCA
#First we need to transform the raw count data
#vst function will perform variance stabilizing transformation
vsdataTALL <- vst(TARGET_DESeqTALL, blind=FALSE) #

## Gene variable
var_genes <- apply(assay(vsdataTALL),1,var)
var_genes <- sort(var_genes, decreasing = T)
# select top x
top_var_genes = names(sort(var_genes,decreasing = T)[1:1000])
#top_var_genes <- var_genes[1:500]
highly_variable_vsdataTALL <- vsdataTALL[top_var_genes,]

tmp <- prcomp(assay(highly_variable_vsdataTALL))
pca_data <- as.data.frame(tmp$rotation[, 1:2])
pca_data$group <- p$group
ggplot(pca_data) + geom_point(aes(x=pca_data$PC1, y =pca_data$PC2,col=pca_data$group),size=3)+ theme_void() + scale_color_manual(values = c("#9BB655FF","#6C74C6","#803342FF","#D89873FF"))

#plot with border also 
ggplot(pca_data, aes (x=pca_data$PC1, y =pca_data$PC2, color = pca_data$group,fill=  pca_data$group )) + geom_point(size=3, shape=21,stroke=1)+ theme_void() + scale_color_manual(values = c("#7A913B","#454EB0","#58222C","#D0804E")) + scale_fill_manual(values =c("#9BB655FF","#6C74C6","#803342FF","#D89873FF"))

```


#### heatmap
```{r}
mat_vst <- assay(vsdataTALL)
gene_vec <- c("HOXA10","HOXA9","HOXA5","MEIS1","HOXB5","NKX2-3","LMO2","LYL1","NKX2-1","TLX1","TLX3","TAL1","BCL11B","RUNX1","TAL2","LMO1","BEX1","BEX2","BEX5")


mat_vst_sub <- mat_vst[gene_vec,]
scaled_mat = t(scale(t(mat_vst_sub))) # row centered matrix

hm_colors = c("dodgerblue1","white","red2")
#to automate scale
hm_limit =c(min(scaled_mat),0, max(scaled_mat))


# sorting sample to appear group together and in stage of arrest order nin TALL
# Définir l'ordre personnalisé
personalized_order <- c("HOXA", "LYL/LMO", "TLX","TAL/LMO")

# specify the order 
clinical_matrix_TARGET_TALL$detailed_class <- factor(clinical_matrix_TARGET_TALL$detailed_class , levels =personalized_order )

# Trier le dataframe en fonction de la colonne 'Nom'
sort_clinical <- clinical_matrix_TARGET_TALL[order(clinical_matrix_TARGET_TALL$detailed_class), ]

all(sort_clinical$TARGET_USI == colnames(scaled_mat))
#need to re order RNA
scaled_mat_order <- scaled_mat[, match(sort_clinical$TARGET_USI, colnames(scaled_mat))]
all(sort_clinical$TARGET_USI == colnames(scaled_mat_order)) # now it's ok

ann <-data.frame(sort_clinical$detailed_class)
cond_detail <- unique(ann$sort_clinical.detailed_class)

# Choisir une palette de couleurs de paletteer

#palette <- as.character(paletteer::paletteer_d("beyonce::X39", n = length(cond_detail)))
palette <- c("#9BB655FF","#6C74C6","#D89873FF","#803342FF")

# Créer une liste avec les associations condition-couleur
color_list <- list()
names(palette) <- cond_detail
color_list <- append(color_list,list('sort_clinical.detailed_class' = palette))

  
colAnn <- HeatmapAnnotation(df = ann,
which = 'col',
col = color_list,
annotation_width = unit(c(1, 4), 'cm'),
gap = unit(1, 'mm'),
annotation_label = "Clinical classification")

#manually slicing
row_split = rep("group1", 19)
row_split[7:8] = "group2"
row_split[9:11] = "group3"
row_split[12:16] = "group4"
row_split[17:19] = "group5"

set.seed(123) # for kmean reproducibility
ComplexHeatmap::Heatmap(scaled_mat_order,show_column_names = FALSE ,cluster_columns = F,row_order = gene_vec, top_annotation = colAnn,col = colorRamp2(hm_limit,hm_colors), column_split = ann$sort_clinical.detailed_class ,show_row_dend = F, heatmap_legend_param = list(title="r norm", direction="vertical"),column_gap =unit(2, "mm"),row_split = row_split,,row_gap = unit(c(2,2,2,6), "mm"))
```

#### Boxplot 
BEX T-ALL subgroup
```{r}
counts <- as.data.frame(assay(vsdataTALL)[c('BEX1','BEX2','BEX5'),])

counts <- data.frame(t(counts), check.rows = F)
all(rownames(counts)== clinical_matrix_TARGET_TALL$TARGET_USI)
counts$class <- clinical_matrix_TARGET_TALL$detailed_class

df_long <- tidyr::gather(counts, key = "gene", value = "expression", -class)


ordre_classes <- c("HOXA", "LYL/LMO", "TLX", "TAL/LMO")
df_long$class <- factor(df_long$class, levels = ordre_classes)

ggplot(df_long, aes(x = gene, y = expression, fill = class)) +
  geom_boxplot(position = position_dodge(width = 0.8))+
  labs(title = "Boxplot des expressions géniques par condition",
       x = "Gène",
       y = "Expression") +
  theme_minimal()+ scale_fill_manual(values=c("#9BB655FF","#6C74C6","#D89873FF","#803342FF"))



# TAL vs all pour les pvalue
# adding a desing
TARGET_DESeqTALL$nonTAL <- factor(TARGET_DESeqTALL$detailed_class %in% c("TLX", "HOXA","LYL/LMO"))
colData(TARGET_DESeqTALL) # Non tall are true
# re run with new desgin
design(TARGET_DESeqTALL)<- ~ 1 + nonTAL
TARGET_DESeqTALL <- DESeq(TARGET_DESeqTALL)
resultsNames(TARGET_DESeqTALL)

res <- results(TARGET_DESeqTALL, contrast = list("nonTAL_TRUE_vs_FALSE"))
res <- as.data.frame(res[order(res$padj),])

res[rownames(res) == "BEX2",]
res[rownames(res) == "BEX1",]
res[rownames(res) == "BEX5",]
```

 
##### ??
```{r}
#testing
TARGET_DESeqALL <- DESeqDataSetFromMatrix(countData=RNA_matrix_TARGET_ALL, 
                              colData=clinical_matrix_TARGET_ALL, 
                              design= ~ simple_class)
TARGET_DESeqALL <- DESeq(TARGET_DESeqALL)
resultsNames(TARGET_DESeqALL) #get comparison that was done
# everything is done with ALAL as reference.

# Plot expression for single gene
plotCounts(TARGET_DESeqALL, gene="BEX2", intgroup="simple_class") 

traf1_counts <- (assay(vsdataALL)['BEX2',])

m <- list(counts = as.numeric(traf1_counts), group = as.factor(TARGET_DESeqALL$simple_class))
m <- as.tibble(m)
q <- ggplot(m, aes(group, counts)) + geom_boxplot() + geom_jitter(width = 0.1)
q <- q + labs(x = "Experimental Group", y = "Vst Counts ", title = "Normalized Expression of BEX2")
q





# adding a desing
TARGET_DESeq$nonTALL <- factor(TARGET_DESeq$simple_class %in% c("AML", "B precursor","B-ALL","ALAL","Ph+"))
colData(TARGET_DESeq) # Non T-ALL are true
# re run with new desgin
design(TARGET_DESeq)<- ~ 1 + nonTALL
TARGET_DESeq <- DESeq(TARGET_DESeq)
resultsNames(TARGET_DESeq)

res1 <- results(TARGET_DESeq, contrast = list("nonTALL_TRUE_vs_FALSE"))
res1 <- res1[order(res1$padj),]
head(res1,n=20)

res1[rownames(res1)== "BEX2",]
cols <- densCols(res1$log2FoldChange, -log10(res1$pvalue))
plot(res1$log2FoldChange, -log10(res1$padj), col=cols, panel.first=grid(),
     main="Volcano plot", xlab="Effect size: log2(fold-change)", ylab="-log10(adjusted p-value)",
     pch=20, cex=0.6)
gn.selected <- abs(res1$log2FoldChange) > 2 & -log10(res1$pvalue) >4
text(res1$log2FoldChange[gn.selected],
     -log10(res1$padj)[gn.selected],
     lab=rownames(res1)[gn.selected ], cex=0.6)


```



### ALL

#### load final matrix
```{r}
clinical_matrix_TARGET_TALL <- readRDS("/workspace/NASBioinfo/LALT/BIOINFO/BEX/TO_UPLOAD_FOR GIT/DATA/BUlkRNA/clinical_matrix_TARGET_ALL.rds")
RNA_matrix_TARGET_TALL <- readRDS("/workspace/NASBioinfo/LALT/BIOINFO/BEX/TO_UPLOAD_FOR GIT/DATA/BUlkRNA/RNA_matrix_TARGET_ALL_convert.rds")
```


```{r}
TARGET_DESeqALL <- DESeqDataSetFromMatrix(countData=RNA_matrix_TARGET_ALL, 
                              colData=clinical_matrix_TARGET_ALL, 
                              design= ~ simple_class)
TARGET_DESeqALL <- DESeq(TARGET_DESeqALL)
```

#### PCA Plot
```{r}
# PCA
#First we need to transform the raw count data
#vst function will perform variance stabilizing transformation
vsdataALL <- vst(TARGET_DESeqALL, blind=FALSE) 

p <- plotPCA(vsdataALL, intgroup="simple_class",returnData = TRUE) 
ggplot(p)+geom_point(aes(x=PC1, y=PC2,col=group),size=2) + theme_void()+
  scale_color_manual(values = c("#FFB01F",
                                "#EB886F"))

# Calculate the variance explained by each principal component
pca <- prcomp(t(assay(vsdataALL)))
variance_explained <- (pca$sdev^2 / sum(pca$sdev^2)) * 100
# Ajouter cette information au dataframe de pcaData
p$PC1_var <- round(variance_explained[1], 1)
p$PC2_var <- round(variance_explained[2], 1)

ggplot(p)+geom_point(aes(x=PC1, y=PC2,col=group),size=2) + 
  xlab(paste0("PC1: ", p$PC1_var[1], "% variance")) +
  ylab(paste0("PC2: ", p$PC2_var[1], "% variance")) +
  scale_color_manual(values = c("#FFB01F",
                                "#EB886F"))

```

#### Heatmap
```{r}
mat_vst <- assay(vsdataALL)
gene_vec <- c("MME","CD19","MS4A1","CD79A","CD79B","CD3D","CD2","CD7","LCK","CD1E","BEX1","BEX2","BEX3","BEX4","BEX5")
mat_vst_sub <- mat_vst[gene_vec,]
scaled_mat = t(scale(t(mat_vst_sub))) # row centered matrix

hm_colors = c("dodgerblue1","white","red2")
#to automate scale
hm_limit =c(min(scaled_mat),0, max(scaled_mat))


# sorting sample to appear group together
sort_clinical <- clinical_matrix_TARGET_ALL[order(clinical_matrix_TARGET_ALL$simple_class),] # sort by one column

sort_clinical <- sort_clinical %>% arrange(simple_class, sample(n())) # sort by group but inside group make it random (to avoid bias by subgroup)
all(sort_clinical$TARGET_USI == colnames(scaled_mat))
#need to re order RNA
scaled_mat_order <- scaled_mat[, match(sort_clinical$TARGET_USI, colnames(scaled_mat))]
all(sort_clinical$TARGET_USI == colnames(scaled_mat_order)) # now it's ok

ann <-data.frame(sort_clinical$simple_class)
cond_simpl <- unique(ann$sort_clinical.simple_class)

# Choisir une palette de couleurs de paletteer

palette2 <- c("#FFB01F", "#EB886F")


# Créer une liste avec les associations condition-couleur
color_list <- list()
names(palette2) <- cond_simpl
color_list <- append(color_list,list('sort_clinical.simple_class' = palette2))

  
colAnn <- HeatmapAnnotation(df = ann,
which = 'col',
col = color_list,
annotation_width = unit(c(1, 4), 'cm'),
gap = unit(1, 'mm'),
annotation_label = "Clinical classification")


## Plot
ComplexHeatmap::Heatmap(scaled_mat_order,show_column_names = FALSE, cluster_columns = F,cluster_rows = F, top_annotation = colAnn,col = colorRamp2(hm_limit,hm_colors), column_split = ann$sort_clinical.simple_class, row_km = 3,row_km_repeats = 500,row_gap = unit(c(2,15), "mm"),show_row_dend = F,
                        heatmap_legend_param = list(title="r norm", direction="vertical"))

#manually slicing
row_split = rep("group1", 15)
row_split[11:15] = "group2"

set.seed(123) # for kmean reproducibility
ComplexHeatmap::Heatmap(scaled_mat_order,show_column_names = FALSE,cluster_columns = F, row_order = gene_vec, top_annotation = colAnn,col = colorRamp2(hm_limit,hm_colors), column_split = ann$sort_clinical.simple_class ,show_row_dend = F, heatmap_legend_param = list(title="r norm", direction="vertical"), row_split = row_split,row_gap = unit(15, "mm"))
```

